#@ load("tiny-pete.lib.star", "tiny_pete")

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: #@ tiny_pete.name
spec:
  rules:
  - http:
      paths:
      - path: /pete
        backend:
          serviceName: #@ tiny_pete.service.name
          servicePort: #@ tiny_pete.service.port