#@ load("tiny-pete.lib.star", "tiny_pete")

---
apiVersion: v1
kind: Service
metadata:
  name: #@ tiny_pete.service.name
spec:
  type: NodePort
  selector: #@ tiny_pete.labels
  ports:
  - port: #@ tiny_pete.service.port
    targetPort: #@ tiny_pete.service.targetPort
